"""User changes
Revision ID: 1afdb23d02ab
Revises: 6aadf3b8c5dc
Create Date: 2023-08-01 13:13:34.336109
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '1afdb23d02ab'
down_revision = '6aadf3b8c5dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=250), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], name="client_fk_address", ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(constraint_name="address_fk_client",
                          source_table="address",
                          referent_table="client",
                          local_cols=['client_id'],
                          remote_cols=["id"])
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_permission',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'permission_id')
    )
    op.create_table('user_group',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.alter_column('user', 'wix_id', existing_type=sa.String(length=100), existing_nullable=False, new_column_name='email')
    op.add_column('user', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('photo', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key("user_fk_client", 'user', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_fk_client", 'user', type_='foreignkey')
    op.drop_constraint("address_fk_client", 'address', type_='foreignkey')
    op.drop_column('user', 'client_id')
    op.drop_column('user', 'title')
    op.drop_column('user', 'photo')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.alter_column('user', 'email', existing_type=sa.String(length=100), existing_nullable=False, new_column_name='wix_id')
    op.drop_table('user_group')
    op.drop_table('group_permission')
    op.drop_table('group')
    op.drop_table('client')
    op.drop_table('address')
    # ### end Alembic commands ###
