"""Add sources column in responses
Revision ID: 2e0fd881dec4
Revises: d9c098726500
Create Date: 2023-08-02 11:40:08.239622
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '2e0fd881dec4'
down_revision = 'd9c098726500'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('sources', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', 'sources')
    # ### end Alembic commands ###
