"""Add created_at for Client and User
Revision ID: 962310d320fc
Revises: bda6e169b2b3
Create Date: 2023-08-07 09:55:57.859595
"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic
revision = '962310d320fc'
down_revision = 'bda6e169b2b3'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_column('client', 'created_at')
    # ### end Alembic commands ###
