"""add date to contact table
Revision ID: a61d85668a73
Revises: 926a03dc09df
Create Date: 2023-09-22 10:02:35.526131
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'a61d85668a73'
down_revision = '926a03dc09df'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'created_at')
    # ### end Alembic commands ###
