"""Add system message tables
Revision ID: bda6e169b2b3
Revises: 2e0fd881dec4
Create Date: 2023-08-03 14:19:21.007164
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'bda6e169b2b3'
down_revision = '2e0fd881dec4'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['custom_question_id'], ['custom_question.id'], name="custom_message_fk_custom_question", ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name="custom_message_fk_user", ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_message')
    op.drop_table('custom_question')
    # ### end Alembic commands ###
