"""Segregate response timestamps
Revision ID: bfc4c60e8d94
Revises: 962310d320fc
Create Date: 2023-08-09 09:52:13.313948
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'bfc4c60e8d94'
down_revision = '962310d320fc'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('response', sa.Column('human_created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('response', sa.Column('human_updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.alter_column('response', 'created_at', existing_type=sa.DateTime(), existing_nullable=False, new_column_name='assistant_created_at', existing_server_default=sa.func.now())
    op.alter_column('response', 'updated_at', existing_type=sa.DateTime(), existing_nullable=False, new_column_name='assistant_updated_at', existing_server_default=sa.func.now())
    # ### end Alembic commands ###
    response = sa.table('response',
                        sa.column('human_created_at', sa.DateTime()),
                        sa.column('human_updated_at', sa.DateTime()),
                        sa.column('assistant_created_at', sa.DateTime()),
                        sa.column('assistant_updated_at', sa.DateTime())
                        )
    op.execute(response.update().values(human_created_at=response.c.assistant_created_at))
    op.execute(response.update().values(human_updated_at=response.c.assistant_updated_at))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('response', 'assistant_created_at', existing_type=sa.DateTime(), existing_nullable=False, new_column_name='created_at', existing_server_default=sa.func.now())
    op.alter_column('response', 'assistant_updated_at', existing_type=sa.DateTime(), existing_nullable=False, new_column_name='updated_at', existing_server_default=sa.func.now())
    op.drop_column('response', 'human_updated_at')
    op.drop_column('response', 'human_created_at')
    # ### end Alembic commands ###
