"""cookie table and deleted case table
Revision ID: fde8532aa464
Revises: bfc4c60e8d94
Create Date: 2023-09-21 14:04:28.585543
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'fde8532aa464'
down_revision = 'bfc4c60e8d94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cookie',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('token', sa.String(length=50), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('expires_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('case')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
                    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('title', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
                    sa.Column('status', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
                    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
                    sa.Column('updated_at', sa.DATETIME(), autoincrement=False, nullable=False),
                    sa.Column('closed_at', sa.DATETIME(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='case_fk_user', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name='PK__case__3213E83F0263CE85')
                    )
    op.drop_table('cookie')
    # ### end Alembic commands ###
